change formatting

diff --git a/src/files/base/usr/bin/alpine-update b/src/files/base/usr/bin/alpine-update
--- a/src/files/base/usr/bin/alpine-update
+++ b/src/files/base/usr/bin/alpine-update
@@ -94,7 +94,7 @@ update_boot() {
     mkdir -p /boot/EFI/BOOT/ /boot/limine
     cp /usr/share/limine/limine-bios.sys /boot/limine
     cp /usr/share/limine/BOOTX64.EFI /boot/EFI/BOOT/
-    limine bios-install "${dev}" > /dev/null
+    limine bios-install "${dev}"
   fi
 
   # Generate Limine configuration
@@ -121,13 +121,13 @@ EOF
 # Ensure /boot is mounted and get the device
 dev=$(findmnt -n -o SOURCE /boot | sed 's/p\?[0-9]*$//')
 if [ -z "${dev}" ]; then
-  echo "/boot is not mounted"
+  echo "/boot is not mounted" >&2
   exit 1
 fi
 
 image=${ALPINE_IMAGE:-$(get_config "image")}
 if [ -z "$image" ]; then
-  echo "No image specified in /boot/alpine/config.yaml"
+  echo "Unable to determine image" >&2
   exit 1
 fi
 
